### ISSUE TITLE
Advanced options fails to add printer ID into printer.cfg

### ISSUE THREAD

**Issue by ScotchTape** [th33xitus/KIAUH#1]
When someone just installs and doesn't have a printer installed and tries to flash or set the printer with the advanced option later, it fails because there is no backup directory at that point in time.
`## Identifying the correct USB port ...
Make sure your printer is the only USB device connected!

## The ID of your printer is:
/dev/serial/by-id/usb-marlinfw.org_Marlin_USB_Device_08FFE001AF3E08845CB50E97F50020C7-if00

Do you want to write this ID to your printer.cfg now? (Y/n):
cp: cannot create regular file '/home/pi/backup/printer.cfg.2020-05-25_140045.backup': No such file or directory`

**Comment by th33xitus** [comment]
A simple fix should be available now, please report back if further issues occur.
For now i am closing this issue.
