### ISSUE TITLE
mjpg-streamer fix for Logitech C270

### ISSUE THREAD

**Issue by AnVa** [th33xitus/kiauh#105]
First of all, thank you so much for the work you have done!

I have a problem with Logitech C270 with Rpi 3B. I found a solution that fixes it

`sudo service webcamd restart`

maybe you should add this to auto start config of Rpi

`sudo nano /etc/rc.local`

`echo`
`echo "Fix Logitech C270 camera"`
`echo`
`sudo service webcamd restart`
`/root/bin/webcam2d`
`exit 0`

Thank you!

**Comment by th33xitus** [comment]
I don't quite understand why editing the rc.local is necessary for restarting the webcamd service. You can restart the webcamd service from within Mainsail or Fluidd iirc ?

**Comment by AnVa** [comment]
Hi @th33xitus 
I can not. But a lot of people have the same problem
https://www.reddit.com/r/octoprint/comments/iwabfn/webcam_image_is_just_white_noise_logitech_c270/
https://www.reddit.com/r/octoprint/comments/ihivnv/logitech_c270_malfunction_white_noise_in_octoprint/

The problem is solved if i restart the service while loading Rpi

It is not issue for kiauh tool. I thought that this information might help someone, so I added it here 

thank you
