### ISSUE TITLE
Option to Restart Services?

### ISSUE THREAD

**Issue by leandrotoledo** [th33xitus/kiauh#108]
Not sure if I missed it, but when running multiple instances it'd be good to have an option in the batch menu that allows to restart services.

e.g. running multiple instances of Klipper and Moonraker, using the kiauh.sh client, restart Moonraker for printer_2.

Thanks for this awesome helper!

**Comment by th33xitus** [comment]
Hi,

just start KIAUH and in the main menu type:
`start <service>`
`stop <service>`
`restart <service>`

`<service>` can be: klipper, moonraker, dwc and octoprint 🙂

**Comment by leandrotoledo** [comment]
Oh wow, that was fast! Thanks a lot!
