### ISSUE TITLE
Submenu clarification to "back" from "quit"

### ISSUE THREAD

**Issue by The-Monkey-King** [th33xitus/kiauh#112]
Submenus reuse the quit_footer from general_ui.sh to quit the submenu and revert back to main menu. 

I proposed (PR #111 ) adding a back_footer to general_ui.sh and editing the submenus to use the word "back" to reflect the idea that you are going back to the main menu and not quitting the program. Quit is reserved for the main menu to quit the application. 

This is my very first PR so please excuse if I have done this wrong.

**Comment by th33xitus** [comment]
Awesome!
I was actually about to do that change myself but now i can also just use your PR. I was told more than once, that "quit" wasn't the best choice there. I will have a look at the PR, test it and if it looks good, i will merge it soon. Thanks!

**Comment by The-Monkey-King** [comment]
Ooops. I forgot to update upload_log.sh. Added to PR

**Comment by th33xitus** [comment]
Thank you! Merged :)
