### ISSUE TITLE
NGINX running as www-data by default causing 403 error

### ISSUE THREAD

**Issue by icase81** [th33xitus/kiauh#121]
Did a clean Ubuntu Server 20.04 install on an AtomicPi. Have another one running everything with Fluidd just fine, but this one nginx kept giving a 403 error. fluidd-error.log just listed 'permission denied'. Checking /etc/nginx/nginx.conf revealed nginx running as www-data, which didn't have permissions to /home/username/fluidd. 

Solution:
Changed the user running nginx to my username and restarted nginx. Worked fine after that.

I've done like 6 or 7 kiauh installs and not had this issue before. I'm not really sure what changed, but the version used on this one obviously newer than others.

**Comment by th33xitus** [comment]
I can't reproduce that issue on my Ubuntu 20.04 Server VM and therefor i don't think that this is an issue with KIAUH.
That's the common way how NGINX is set up with the worker running as www-data.
You should have checked file and folder permissions rather then just altering the nginx.conf which is usually, for our usecases, already set up correctly.
