### ISSUE TITLE
moonraker requires python 3.7

### ISSUE THREAD

**Issue by ginpigin** [th33xitus/kiauh#125]
I'm trying to install the klipper on a laptop, it's worth building mint based on 19.3. the system has python 3.6.9 by default, tried to install 3.7.5 manually, enabled this version by default. python --version gives 3.7.5 but moonraker gives the same error! How to fix it? tried installing like this https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/

**Comment by th33xitus** [comment]
> I wrote that version 3.7.5 is installed in the system, but the installer does not see it.

KIAUH checks for the correct python 3 version with the following command:
`python3 --version`

Whats the output of that command for you?

**Comment by th33xitus** [comment]
> > Well, please report back then when your system is up and running again.
> 
> https://fastpic.org/view/116/2021/1017/_e10a0f36c7d6690322579b4ade87fe63.jpg.html https://fastpic.org/view/116/2021/1017/_eaca04825d376305e5ee0fc3e22bb621.jpg.html

Okay so what i see is:
`python --version` -> Python 2.7.17
`python3 --version` -> Python 3.6.9

And therefore the minimum required python version of 3.7 for Moonraker is not met and you can't install Moonraker.
