### ISSUE TITLE
webcamd.service causes log spamming and eventually run out of memory

### ISSUE THREAD

**Issue by plloppii** [th33xitus/kiauh#127]
Recently came across this while using this amazing script.
I installed klipper, moonraker, and fluidd all through kiauh script. 

I did want to have the option to add a webcam in the future so I selected yes to download webcamd.
However in doing so, my raspberry pi ran out of memory a few days later because of the continuous rebooting of the webcamd service. 

Source of issue, in `webcamd.service`
`RestartSec=10`

I don't know if this is a feature or a bug, but it doesnt seem very right to be spamming the logs if the webcamd service cannot come up.
I think a simple reboot of the pi when would work fine to get the webcam initialized.

**Comment by th33xitus** [comment]
I just pushed a commit for adding a logrotate rule.
The rule is set identical to the one found in the current MainsailOS release.
