### ISSUE TITLE
Missing cmake dependency for correct mjpg-streamer compilation / installation

### ISSUE THREAD

**Issue by wykys** [th33xitus/kiauh#139]
Missing cmake dependency for correct mjpg-streamer compilation / installation.

It would be a good idea to install it on your system before installing mjpg-streamer.

**Comment by th33xitus** [comment]
https://github.com/th33xitus/kiauh/blob/master/scripts/install_mjpg-streamer.sh#L22

Last entry in that array of dependencies is cmake. So it should be installed before anything else is done.

**Comment by wykys** [comment]
I'll try to test it again in a clean system as I have time off.

**Comment by th33xitus** [comment]
For any additional feedback pls continue in #149
