### ISSUE TITLE
OctoPrint backup (missing destination file operand)

### ISSUE THREAD

**Issue by Fredy12335** [th33xitus/kiauh#143]
Hello!
I have a problem with octoprint backup. 

```
###### Creating OctoPrint backup ...
###### Timestamp: 211115-1449
cp: missing destination file operand after '/home/pi/kiauh-backups/octoprint-backups/211115-1449'
Try 'cp --help' for more information.
>>>>>> Backup complete!

```
I already managed to make a backup from Kilpper.
But I need backup of octoprint too.

I tried after the stop octoprint command, but the same problem.

PS: I have already made a backup of the octoprint (with octoprint interface) so it is not urgent.

And OFC thanks this awesome stuff!

**Comment by th33xitus** [comment]
Thanks for reporting! Should be fixed by now! :)
