### ISSUE TITLE
Klipper UDS service bug

### ISSUE THREAD

**Issue by ils15** [th33xitus/kiauh#144]
Installed Klipper as usual and cannot run correctly

https://i.imgur.com/zaKDm09.png

Please check if the Klipper service is running and an UDS (Unix Domain Socket) is configured.

**Comment by th33xitus** [comment]
Can you please describe what do you think the issue with KIAUH is in this situation?

Can you please post the output of the following command, once you logged in via ssh:
`cat /etc/systemd/system/klipper.service`

**Comment by ils15** [comment]
Hi, because i used kiauh and no problem
cannot find klipper in this directory

cat: /etc/systemd/system/klipper.service: No such file or directory
But kiauh showing klipper installed 

https://i.imgur.com/RYKlZua.png

**Comment by ils15** [comment]
Hi...
Fixed using a old klipper version
