### ISSUE TITLE
Add additional repos

### ISSUE THREAD

**Issue by LMS0815** [th33xitus/kiauh#152]
### Is your feature request related to a problem? Please describe

Kindly add the option to add the repo list and/or extend it.

### Describe the solution you'd like

In addition to the current repositories, I would appreciate if you can add/support of the  **Desuuuu** repo as well including the different branches (especially: **dgus-display**)

[Desuuuu repo](https://github.com/Desuuuu/klipper.git)

### Describe alternatives you've considered

Manual Installation
```
sudo service klipper stop
cd ~
rm -rf ~/klipper
git clone --single-branch --branch dgus-display https://github.com/Desuuuu/klipper
sudo service klipper start
```

### Additional information

The manual installation is causing issues with fluidd software update.

**Comment by properlypurple** [comment]
Adding here that this will also help with installing a fork like this one
https://github.com/PrusaOwners/klipper

**Comment by LMS0815** [comment]
THANK YOU!
