### ISSUE TITLE
Corrupt .git objects

### ISSUE THREAD

**Issue by rlaferla** [th33xitus/kiauh#153]
### What happened

/=======================================================\
|     ~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~     |
|        Klipper Installation And Update Helper         |
|     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     |
\=======================================================/
error: object file .git/objects/32/3268ea02700b2fd3b6accda310845ba29c894e is empty
error: object file .git/objects/32/3268ea02700b2fd3b6accda310845ba29c894e is empty
fatal: loose object 323268ea02700b2fd3b6accda310845ba29c894e (stored in .git/objects/32/3268ea02700b2fd3b6accda310845ba29c894e) is corrupt
fatal: the remote end hung up unexpectedly
error: object file .git/objects/32/3268ea02700b2fd3b6accda310845ba29c894e is empty
error: object file .git/objects/32/3268ea02700b2fd3b6accda310845ba29c894e is empty
fatal: loose object 323268ea02700b2fd3b6accda310845ba29c894e (stored in .git/objects/32/3268ea02700b2fd3b6accda310845ba29c894e) is corrupt
error: object file .git/objects/3f/7cc53baacfd8895386070d3f7dd5ad85903163 is empty
error: object file .git/objects/3f/7cc53baacfd8895386070d3f7dd5ad85903163 is empty
fatal: loose object 3f7cc53baacfd8895386070d3f7dd5ad85903163 (stored in .git/objects/3f/7cc53baacfd8895386070d3f7dd5ad85903163) is corrupt
fatal: the remote end hung up unexpectedly
error: object file .git/objects/3f/7cc53baacfd8895386070d3f7dd5ad85903163 is empty
error: object file .git/objects/3f/7cc53baacfd8895386070d3f7dd5ad85903163 is empty
fatal: loose object 3f7cc53baacfd8895386070d3f7dd5ad85903163 (stored in .git/objects/3f/7cc53baacfd8895386070d3f7dd5ad85903163) is corrupt

### What did you expect to happen

No error messages and the ability to update

### How to reproduce

Run kiauh, and then 2 for update

**Comment by th33xitus** [comment]
Not a KIAUH bug. Something else has corrupted the corresponding data. Re-install the affected component.
