### ISSUE TITLE
Multi printer (Moonraker) detection detects Moonraker telegram bot as a printer

### ISSUE THREAD

**Issue by Lupusalix** [th33xitus/kiauh#156]
### What happened

When trying to install a theme for mainsail, the check for multiple printers thinks that the telegram bot is a second printer.

### What did you expect to happen

It shouldn't recognize the telegram bot service configuration as a printer.

### How to reproduce

Install Mainsail, klipper, moonraker, telegram bot, Try to install a mainsail theme.

### Additional information

/scripts/ms_theme_installer.sh
Line 74 `printer_count=$(ls /etc/systemd/system/moonraker*.service | wc -l)` checks true for the telegram bot.
```
ls /etc/systemd/system/moonraker*
/etc/systemd/system/moonraker.service  /etc/systemd/system/moonraker-telegram-bot.service
```

**Comment by Lupusalix** [comment]
@th33xitus 
Thank you very much. Works flawlessly :D

**Comment by th33xitus** [comment]
@Lupusalix Yw, but keep in mind, that is the develop branch you probably have checked out now. I plan to merge the state of that branch to master in the next days. Then this issue here will auto-close as well.
