### ISSUE TITLE
bytes_invalid=7    print lean

### ISSUE THREAD

**Issue by bihailantian655** [th33xitus/kiauh#161]
### Linux Distribution

ubuntu  and  armbian

### What happened

if print  a cylinde

machine  with   marlin   work  fun ，

same  machine  with  klipper   print will  incline like a    Leaning Tower of Pisa

bytes_read=106438 bytes_retransmit=496 bytes_invalid=7 send_seq=5730 receive_seq=5718 ,    

in  the  klippy log   ， there are  a lots  of            bytes_invalid=7       ,  is  this  normal?

 

### What did you expect to happen

working normal

### How to reproduce

i try flash  klipper many times ， it  happed  everytime。

install  ubuntu on  desktop and   orangepi   。

dont know why ，

**Comment by th33xitus** [comment]
Errors in klipper logs are not KIAUH related. I suggest you visit the Klipper Discord or Discourse and ask the people there for a solution or the cause of your issue.
