### ISSUE TITLE
Use 'q' to quit kiauh from any menu

### ISSUE THREAD

**Issue by cbc02009** [th33xitus/kiauh#162]
### Is your feature request related to a problem? Please describe

Nope, this is not related to a problem other than me having to go through the immense effort to press one additional key.

### Describe the solution you'd like

It would be nice if more menus recognized q as a quit kiauh option.

### Describe alternatives you've considered

I could just keep entering b until I return to the main menu.

### Additional information

I understand this is very low priority. Just thought it would be useful.

**Comment by th33xitus** [comment]
To understand you correct i need an answer to the following question:
Do you want to directly quit KIAUH at all (so exiting the program) or just quickly get back to the main menu (stay in KIAUH)?

**Comment by cbc02009** [comment]
I would like to directly quit KIAUH from menus like the install menu without having the hit 'b' to go back to the main menu first.

**Comment by th33xitus** [comment]
You can quit KIAUH at any point in time with pressing `CTRL+C` if your intent is to close it anyways.
It's a general shortcut to break out of a command or process in a terminal.

**Comment by cbc02009** [comment]
I could have sworn I tried ctrl +c and it didn't work. Of course retesting it now works fine, so it must have been user error...
