### ISSUE TITLE
Integrating Android KlipperScreen config to KIAUH

### ISSUE THREAD

**Issue by onehate** [th33xitus/kiauh#165]
### Is your feature request related to a problem? Please describe

Its not a problem but a FR

### Describe the solution you'd like

Thank you for a great setup automation system, love it.

Would not want to sound cliche but, I believe the ability to run KlipperScreen thru an old android phone using XSDL is a very nice way of stopping old phones from going to landfills prematurely. It would be great if KlipperScreen Android and ADB configuration could be done through the CLI interface of KIAUH. Being able to install ADB/tools and automating the KlipperScreen service modification (if needed) would be awesome.

The manual version of this is done as an example at

[https://klipper.discourse.group/t/how-to-klipperscreen-on-android-smart-phones/1196](url)

**Comment by th33xitus** [comment]
Hi, thanks for your suggestion.

Basically the same answer i gave in #166 applies here as well.
https://github.com/th33xitus/kiauh/issues/166#issuecomment-1013940026

With every new feature i add, i have to invest time to also support it or fix it if something breaks. Which i can't really do if im not able to even test those things myself. So i prefer such things to be kept in guides like the one you posted. Klippers discourse forum is the better place for those kind of guides. For KIAUH i rather stick to support installations of basic components revolving around Klipper, but not those going into very specific niches.
