### ISSUE TITLE
Kiauh fails to install cmake on Allwinner H5 (Armbian)

### ISSUE THREAD

**Issue by dmason1992** [th33xitus/kiauh#167]
### Linux Distribution

Armbian (Image provided here for the mellow fly gemini board [on github](https://github.com/Mellow-3D/Fly-Gemini/blob/main/Instructions%20for%20use/Gemini%20introductory%20tutorial.pdf)) 

### What happened

I tried to install mjpeg-streamer via the install menu in kiauh. There is no warning message that it failed but it also doesn't fully install. Then none of the mjpeg commands work. After some digging I figured i'd try to manually install it and that is when i realised cmake was the only dependency not installed. After installing cmake i used kiauh to remove then install mjpeg-streamer and it installed correctly with output to the console that supported mjpeg-streamer being built.

### What did you expect to happen

mjpeg streamer to be installed and working

### How to reproduce

flash clean image to the allwinner H5 based board (Fly gemini) and then try to install mjpeg-streamer. Then try to run any mjpeg commands.

### Additional information

#149 references the same issue but on Ubunutu

_No response_

**Comment by Xeroxxx** [comment]
Can not confirm on H5. I don't see any relation between processor and mjpeg-streamer.

Using Armbian Bullseye, so stick to supported image from armbian.
