### ISSUE TITLE
dependencies for Input Shaping

### ISSUE THREAD

**Issue by madhunm** [th33xitus/kiauh#169]
### Is your feature request related to a problem? Please describe

No, this is a pure feature request

### Describe the solution you'd like

It would be nice if kiauh could install the dependencies for input shaping; viz.,

1. Numpy
2. python3-numpy
3. python3-matplotlib

add klipper-mcu-start.sh to rc.d and setup a linux process and add that to printer.cfg

**Comment by th33xitus** [comment]
duplicate of #103
