### ISSUE TITLE
Adding additional hosts script in Moonraker install doesn't append to moonraker.conf

### ISSUE THREAD

**Issue by tumbleweedlabs** [th33xitus/kiauh#17]
Tested with both IPV6 and IPV4 addresses. Neither were appended to moonraker.conf. Example photos can be seen here: https://imgur.com/a/MAMrWcr

Expected behavior: The script indicates as many IP addresses as desired may be added and when finished, type done. Then the IP addresses should be appended to the moonraker.conf file. 

Exhibited behavior: Entering one IP address and striking return continues the script with no option to add more. IP address entered is not appended.

**Comment by th33xitus** [comment]
Thanks for reporting.
An additional `break` sneaked into the wrong section of the script.
Fixed.

**Comment by tumbleweedlabs** [comment]
You're the best.
