### ISSUE TITLE
Installing Fluidd but still shows Mainsail as installed

### ISSUE THREAD

**Issue by acosano** [th33xitus/kiauh#178]
### Linux Distribution

Installation of Fluidd

### What happened

In the software update it shows Fluidd and Mainsail but only Fluidd is installed.

### What did you expect to happen

There should not be any Mainsail references at all as it is not install ed. It should be only Fluidd.

### How to reproduce

Install OS 64bit lite. Klipper, Moonraker and then  Reboot and check Software Updates .
![image_2022-03-08_083226](https://user-images.githubusercontent.com/13814090/157121205-9c4491c6-cefc-41c7-ac80-fb682489bcac.png)

**Comment by th33xitus** [comment]
This is not a bug, remove Mainsail from the update manager section of your moonraker.conf
