### ISSUE TITLE
Octoprint installation via kiauh with https support possible ?

### ISSUE THREAD

**Issue by Mrdindon** [th33xitus/kiauh#180]
### Is your feature request related to a problem? Please describe

Not really a problem but having https enable is better I think.

### Describe the solution you'd like

Somehow make it possible to install/enable haproxy via kiauh to support octoprint and maybe fluidd/mainsail https connection ?

**Comment by th33xitus** [comment]
I will not support installing haproxy as it conflicts with NGINX which is a requirement for Mainsail and Fluidd.
Also https support depends on creating custom certificates and probably a lot more im not even aware of. So once someone found out how to make all this happen, i could try and automate it. Although installing certificates must happen on all devices the user uses afaik. So pretty much nothing that can be automated. I close this for the time being.
