### ISSUE TITLE
Webinterface not loading tornado with 2 printers

### ISSUE THREAD

**Issue by DrBabbage** [th33xitus/kiauh#181]
### Linux Distribution

I want to run 2 printers on one pi 3, running mainsail. I made a fresh install of debian bullseye, started with klipper, then moonraker and then mainsail and still get this error.

`{"error": {"code": 404, "message": "Not Found", "traceback": "Traceback (most recent call last):\n\n  File \"/home/pi/moonraker-env/lib/python3.9/site-packages/tornado/web.py\", line 1681, in _execute\n    result = self.prepare()\n\n  File \"/home/pi/moonraker/moonraker/app.py\", line 904, in prepare\n    raise tornado.web.HTTPError(404)\n\ntornado.web.HTTPError: HTTP 404: Not Found\n"}}`

[klippy_1.log](https://pastebin.com/7wMFihUG)
[moonraker_1.log](https://pastebin.com/AMqFDMKe)

### What happened

Only get Json Code displayed when I try to access one of those printers after fresh install

### What did you expect to happen

show mainsail

### How to reproduce

fresh install 
install 2 instances of klipper, moonraker and one mainsail instance on a raspberry pi on bullseye.

Damn I am stupid.
This is the moonraker api not the mainsail api. The last one is on port 8080

**Comment by th33xitus** [comment]
What did you type in the browser to try and access mainsail?
