### ISSUE TITLE
can I run octoklipper and mainsail at the same time for one printer? 

### ISSUE THREAD

**Issue by cribbageSTARSHIP** [th33xitus/kiauh#186]
### Is your feature request related to a problem? Please describe

Not a problem, but I want to be able use octoklipper and mainsail at the same time. Octoklipper for spaghetti detective and gpio plugins, and mainsail to manage my klipper instance.

### Describe the solution you'd like

To access octoklipper from IP:port# and use:
- the gpio plugins for actuating relays; and
- allow spaghetti detective to pause and start prints when needed

And to use mainsail for running and manipulating my j klipper instance.

### Describe alternatives you've considered

I've heard there is a TSD plugin for Moonraker but it's not rock solid yet.

**Comment by th33xitus** [comment]
It is possible, but make sure to **NOT** start off off a OctoPi image. By default OctoPrint uses a different reverse proxy server than Mainsail. So the best thing probably would be to start off with a clean RaspberryPi OS and install both, OctoPrint and Mainsail. Alternatively MainsailOS should also work, and then install OctoPrint with KIAUH on it.

> I've heard there is a TSD plugin for Moonraker but it's not rock solid yet.

Yes there is, and im also not aware of how stable it is. Iirc the devs don't recommend it for production use yet.
https://github.com/TheSpaghettiDetective/tsd-moonraker
