### ISSUE TITLE
How to modify the interface of KlipperScreen with the screen to adapt to my MKS TS35?

### ISSUE THREAD

**Issue by MS1987** [th33xitus/kiauh#188]
### Is your feature request related to a problem? Please describe

I use OrangePi, and want to use KlipperScreen with a [MKS TS35](https://github.com/willngton/3DPrinterConfig/tree/main/mks_ts35)(which uses spi interface).
I have installed Klipper and KlipperScreen through Kiauh, but no display now.Of course, this is normal, as the screen interface is different from RPI. So I think I should modify the interface definition of KlipperScreen to the screen, is there any way? Thanks!

### Describe the solution you'd like

Tell me how to modify the interface of KlipperScreen with the screen to adapt to my MKS TS35

**Comment by th33xitus** [comment]
I am not the developer of KlipperScreen so I can't give you an answer to that, sorry.
So for your request it is probably best to ask at https://github.com/jordanruthe/KlipperScreen
