### ISSUE TITLE
KIAUH stops large thumbnail from displaying after removing the Voron branding in G-code page

### ISSUE THREAD

**Issue by LazaroFilm** [th33xitus/kiauh#19]
Well, th3xitus, you already know about this. 

![Screen Shot 2020-09-21 at 4 50 23 PM](https://user-images.githubusercontent.com/18351100/93831077-e7c7ed80-fc3f-11ea-83b0-cd403fb74400.png)

Temporary solution: Update Mainsail via KIAUH and don't reapply the branding removal.

**Comment by th33xitus** [comment]
This bug is "fixed".
The function for removing the brandings got removed in `3257c84`.
UI customizations are planned for mainsail in the future (no ETA).
