### ISSUE TITLE
Result codes of install steps are not checked; KIAUH reports false positive success

### ISSUE THREAD

**Issue by compucat** [th33xitus/kiauh#193]
### Linux Distribution

Distro-agnostic issue; tested on Ubuntu groovy

### What happened

If, during the installation of a component, one of the install steps fails, KIAUH will proceed as if the component installed successfully. For example, installing Klipper requires git as a dependency, and KIAUH will attempt to call apt to install it. However, if another instance of dpkg holds the lock file already, apt will fail to execute. 

Testing should be performed on all install options; I only checked Klipper and Fluidd. Interestingly enough, installing Fluidd fails - but only because Moonraker is not installed, not because the dependencies failed to install. Klipper's installation will "continue" despite errors, all the way up to creating the systemd service.

In the case of Klipper, this leaves the system in a broken state. The main menu will display Klipper as "not installed" - but attempting to install Klipper again errors out due to the systemd service being present. The Klipper uninstall script must be run before another install can be attempted.

### What did you expect to happen

KIAUH should abort (citing failure to install dependencies) or retry, and it should not leave the system in a broken state.

### How to reproduce

There may be other failure conditions, but APT is convenient.

First, use dpkg/apt/similar to lock either the dpkg or apt locks. This prevents another apt instance from installing packages.

Ensure that a required dependency is missing - for example, git.

From KIAUH main menu, select (1) to install, then (1) for Klipper. 

Observe that KIAUH will attempt to install git using apt. apt will fail, but KIAUH will proceed anyway. Success is similarly not checked when creating the Python venv.

**Comment by th33xitus** [comment]
Yes, that is known. Error handling needs a lot of improvement. And i am working on that for version 4 of the script.
