### ISSUE TITLE
[v4-rc] klipper update bug

### ISSUE THREAD

**Issue by mlaci001** [th33xitus/kiauh#196]
### Linux Distribution

RPI Debian Bullseye

### What happened

update klipper:
/home/klipper/klippy-env/bin/pip: line 3: import: command not found
/home/klipper/klippy-env/bin/pip: line 4: import: command not found
/home/klipper/klippy-env/bin/pip: line 5: from: command not found
/home/klipper/klippy-env/bin/pip: line 7: syntax error near unexpected token `('
/home/klipper/klippy-env/bin/pip: line 7: `    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])'

### What did you expect to happen

Normally updated klipper.

### How to reproduce

Menu:
2) [Update]
1) [Klipper] 

### Additional information

line 420:     /bin/bash "${KLIPPY_ENV}/bin/pip" install -r "${KLIPPER_DIR}/scripts/klippy-requirements.txt"
I think the "-c" parameter is missing
The original method works:
"${KLIPPY_ENV}"/bin/pip install -r "${KLIPPER_DIR}"/scripts/klippy-requirements.txt
I

**Comment by th33xitus** [comment]
I assume you are not using the current KIAUH master, correct? You checked out the v4-rc branch?

**Comment by mlaci001** [comment]
Sorry.
Yes I use the v4-rc branch.
I also saw another error in the update menu under "6) [PrettyGCode]".
![kiauh-update-v4-rc](https://user-images.githubusercontent.com/84029329/168240970-93cdd89f-21e1-4fb8-ae66-c87bc112ed13.jpg)

**Comment by th33xitus** [comment]
Okay thanks i will have a look.
The issue you mentioned earlier is fixed. I simply reverted to the previous way of calling scripts or commands. So without `/bin/bash` in front of them. Not quite sure why i changed that if it worked flawless lol...
