### ISSUE TITLE
Remove branding

### ISSUE THREAD

**Issue by LazaroFilm** [th33xitus/kiauh#20]
So since the remove branding is now gone, I figured out I would do it myself because I really don't like the image in the background of the menu. I changed it to a 50% gray image with the same name as the other and simply replaced the image in `/home/pi/mainsail/img` folder. It gi

Attached is the blank background image I'm now using. 
![bg-navi 519d7209](https://user-images.githubusercontent.com/18351100/94026765-12bd5900-fd88-11ea-8a96-aff36fea91ba.jpg)

**Comment by th33xitus** [comment]
This is no issue with KIAUH, therefore i will close this now.
Please use this issue tracker only for real issues with the script or feature request. Thank you.
