### ISSUE TITLE
haproxy not uninstalling with kiauh

### ISSUE THREAD

**Issue by zogthegreat** [th33xitus/kiauh#201]
### Linux Distribution

Ubuntu

### What happened

I install Kiauh on Ubuntu and I ran into a problem with not being able to connect to Mainsail web interface. After several reinstalls, I noticed that haproxy wasn't uninstalling when I pressed "1" to uninstall it. When I tried the IP for Mainsail, I would get "The OctoPrint server is currently not running".

`pi@octopi:~ $ systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Mon 2022-04-18 09:00:03 EDT; 1min 0s ago
Docs: man:nginx(8)
Process: 3553 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
Process: 3554 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
Apr 18 09:00:00 octopi systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 18 09:00:00 octopi nginx[3554]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 18 09:00:01 octopi nginx[3554]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 18 09:00:01 octopi nginx[3554]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 18 09:00:02 octopi nginx[3554]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 18 09:00:02 octopi nginx[3554]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Apr 18 09:00:03 octopi nginx[3554]: nginx: [emerg] still could not bind()
Apr 18 09:00:03 octopi systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Apr 18 09:00:03 octopi systemd[1]: nginx.service: Failed with result 'exit-code'.
Apr 18 09:00:03 octopi systemd[1]: Failed to start A high performance web server and a reverse proxy server.`

After I used apt to remove it, everything seems to be working properly. I can log into the web interface and everything seems normal.

Not sure if this is a bug or a PEBKAC, but another user on reddit had the same problem:

[https://www.reddit.com/r/klippers/comments/u6bt71/cant_connect_to_mainsail_web_interface/](url)

### What did you expect to happen

I expected to be able to immediately log into the Mainsail interface

### How to reproduce

Install Kiauh and then try to uninstall haproxy

**Comment by th33xitus** [comment]
The error message you posted is typical for haproxy conflicting with nginx. Thats why kiauh prompts for removing haproxy. But i am not sure why it seems that this didn't happen correctly. kiauh also just runs apt-get remove.
Ubuntu doesn't come pre-installed with haproxy. Are you sure you used Ubuntu and not OctoPi?

**Comment by zogthegreat** [comment]
Hi @th33xitus 

This was about a month or so ago, so I don't remember exactly how I had things setup. I _think_ that I was running Mainsail Pi, but I'm not certain. I'll try to set things up again and try to reproduce the problem. I also posted a question to another user who had the same problem on reddit. I'll post up what his/her setup was/

**Comment by zogthegreat** [comment]
The user on reddit got back to me. He used OctoPi then kiauh to install Klipper, Moonraker and Mainsail. I believe this is what I did also.

[https://www.reddit.com/r/klippers/comments/u6bt71/cant_connect_to_mainsail_web_interface/ia7jeb4/?%24deep_link=true&correlation_id=9d264ddb-ea0d-4e72-90cb-dccab47caea3&ref=email_comment_reply&ref_campaign=email_comment_reply&ref_source=email&%243p=e_as&_branch_match_id=1031229673501918025&utm_medium=Email%20Amazon%20SES&_branch_referrer=H4sIAAAAAAAAA32O4WrDMAyEnyb7l6SLTUIHZQzGXsPIttpqdWyjKIS9%2FWTW3wMbjtN33N1F6vY2jowxkgxQ65AoP0ZT37vJmnpBB9uLysJ0owzJ7Zwu95bqzEc3fek7jmN45kNZ1WD9j0S1Im8q1VwxS5P77GV5bR5kcaHkjEGcFLcC5Q0ouQO9oyzIVwioIMHyjd62JqNlNiJW1yZ25lN4V2QOhRkTCJXsKKp%2FjtNsY%2FQ9win2FpepP5%2BC72MI4O0SAMFojvGqMK6t9rnRMdb083dzAdYKdMv%2FQlvZWYc%2BkV%2Bl94%2BOTwEAAA%3D%3D](url)

**Comment by th33xitus** [comment]
I updated the script and tested it. Im sure haproxy should be correctly removed now. Im closing that issue for now. In case you still encounter the issue, feel free to re-open a new one.

**Comment by zogthegreat** [comment]
Thanks @th33xitus! I'm switching back to Klipper next week. I'll try to replicate the problem. I'll let you know which ever way it goes.
