### ISSUE TITLE
Permission denied when creating Nginx config for Fluidd 

### ISSUE THREAD

**Issue by disaster999** [th33xitus/kiauh#202]
### Linux Distribution

Not sure what this is asking, quite new to this. I am installing this on a Orange Pi 3 LTS board running Debian image from Orange Pi's website

### What happened

First time installing Kiauh on an orangepi, I installed the Debian image, then installed and ran Kiauh. Followed the steps in the menu, installed Klipper first, then Moonraker, then Fluidd. As it was installing Fluidd, it gets to the point where it was installing Nginx I would get an error saying permission denied

###### Checking for the following dependencies:
● nginx
[✓ OK] Dependencies already met!

###### Creating Nginx configuration for Fluidd ...
/home/orangepi/kiauh/scripts/nginx.sh: line 279: /home/orangepi/kiauh/resources/fluidd: Permission denied

Thinking it is something to do with Fluidd, I uninstalled what I have installed so far, and decided to try Mainsail but the same thing happens, saying permission denied for Nginx

Not sure how to proceed from here

### What did you expect to happen

It should just work?

### How to reproduce

Just following the steps prompted on the screen

**Comment by th33xitus** [comment]
Im not quite sure why that permission issue occured.
Though, i pushed a possible fix. I wanted to get my hands on that function anyways, so i just tried a different approach on setting up the config. Please update KIAUH and try again. And please report back if it works now.

**Comment by disaster999** [comment]
I tried updating, didnt work. Tried manually installing Fluidd, that was a big fail and kept crashing my board half way. 

I basically formatted everything and start from scratch again. I think I downloaded an outdated Debian image before cuz I downloaded an more updated version for my board, reinstalled everything and went without a hitch. Fluidd works now.
