### ISSUE TITLE
Error message in "Update Menu"

### ISSUE THREAD

**Issue by LifeDay** [th33xitus/kiauh#203]
### Linux Distribution

 Raspbian GNU/Linux 10 (buster) armv7l

### What happened

Update menu loaded much slower than usual and displayed the error message "fatal: Not a valid object name origin/master" just above entry 6 (PrettyGCode)
![fPaAL6HXpu](https://user-images.githubusercontent.com/11354683/171206803-b7f774e5-753f-4cbf-bc32-9d7031cea8ba.png)

### What did you expect to happen

Usually, no error message is displayed

### How to reproduce

1. Launch KIAUH
2. Perform action 2
3. Error message is displayed

**Comment by th33xitus** [comment]
Thanks for reporting. Should be solved now.

**Comment by LifeDay** [comment]
Tried the fix and it looks like it's working now.
Thanks!
