### ISSUE TITLE
Update All Does not Perform Update

### ISSUE THREAD

**Issue by LifeDay** [th33xitus/kiauh#204]
### Linux Distribution

 Raspbian GNU/Linux 10 (buster) armv7l

### What happened

Update menu shows there are updates for Klipper and Moonraker.
Selecting update all does not perform an update but displays the message, "Everything is already up-to-date!"

### What did you expect to happen

I would have expected Klipper and Moonraker to be updated

### How to reproduce

1. Launch Kiauh
2. Select menu **2) [Update]**
3. Menu shows updates for Klipper and Moonraker are available
4. Select option a) [Update all]
5. Message shows "Everything is already up-to-date!"
![BEEN2VrL0L](https://user-images.githubusercontent.com/11354683/171651070-44aa0922-0425-4703-8a57-c91007aa89b7.png)

### Additional information

The menu is also loading slowly and in a staggered fashion that I don't remember from a week or so ago.

**Comment by JRHeaton** [comment]
I'm experiencing the same issue, and also with a multi-instance installation.

**Comment by th33xitus** [comment]
i was able to reproduce that issue and im working on a solution. not sure why that broke...

**Comment by JRHeaton** [comment]
Still observing this issue in the latest update
