### ISSUE TITLE
README.md should contain minimum configuration steps

### ISSUE THREAD

**Issue by 5ilver** [th33xitus/kiauh#205]
### Is your feature request related to a problem? Please describe

After running the kiauh script the user is left at a documentation dead end. Seeking examples on reddit or youtube is required to proceed.

### Describe the solution you'd like

The readme should contain the minimum set of applications to install and instructions on how to access them. It should also include how one should configure klipper and a microcontroller.

Documentation for this could be links to other documentation in a "next steps" section.

**Comment by th33xitus** [comment]
> After running the kiauh script the user is left at a documentation dead end. Seeking examples on reddit or youtube is required to proceed.

Can you elaborate on that please? I am not quite sure for what exact reason reddit or youtube is required for the overall usage of KIAUH. Are the menus not descriptive enough? Are some things worded too difficult to understand? Im always open for improving descriptions or wordings to make them easier and better to understand.

> The readme should contain the minimum set of applications to install and instructions on how to access them.

There is no minimum set of applications. But if we pretend there is, just to give justification to the existence of KIAUH, then the absolute minimum application to install is Klipper obviously. But that is imho something not worth mentioning in the readme, as i expect every user who is downloading and using KIAUH has already a clear intention what KIAUH should accomplish or what it should help with. Although i agree, that i could add a short overview of the applications KIAUH **can** install again.

> It should also include how one should configure klipper and a microcontroller.

I disagree with that as i do not see this as part of KIAUHs scope. I also expect every user to inform himself/herself **before** even starting with Klipper and therefore the consideration of using KIAUH to install it.
