### ISSUE TITLE
Invalid root path (gcodes)

### ISSUE THREAD

**Issue by linghaokeji** [th33xitus/kiauh#207]
### Linux Distribution

I tried install klipper+moonraker+fluidd on debian buster and debian bulleyes

### What happened

i installed many times on different systems but it still shows (Invalid root path (gcodes))  

### What did you expect to happen

how to solve that problem

### How to reproduce

install on orangepi's debian system (server version) No error is reported during the process

### Additional information

![微信截图_20220605020320](https://user-images.githubusercontent.com/106884033/172019977-61c76a2e-ed02-4415-873e-fc43c86cd43f.png)
![微信截图_20220605020407](https://user-images.githubusercontent.com/106884033/172019979-724d3953-2f2b-41af-9f4a-365ffd944b4b.png)

**Comment by linghaokeji** [comment]
My English is very poor, if there is anything wrong, please forgive me

**Comment by th33xitus** [comment]
You need to make sure that your printer.cfg is valid an Klipper can start without any errors. At that point the error message should disappear.

**Comment by linghaokeji** [comment]
ok I will try it later,I will report the progression.thanks

**Comment by linghaokeji** [comment]
I tried to connect the mcu board, the g-code upload button is red.it says : root is not available.Please check your logs

**Comment by th33xitus** [comment]
Please join the Klipper Discord to get more help: https://discord.klipper3d.org/

This issue is not KIAUH related. And it seems as a general configuration issue.
