### ISSUE TITLE
Flashing BTT Octopus PRO

### ISSUE THREAD

**Issue by DragonFlyer007** [th33xitus/kiauh#209]
### Is your feature request related to a problem? Please describe

Not seeing this card in the supported section

### Describe the solution you'd like

Support for this card, or what other card i can choose to install?

**Comment by th33xitus** [comment]
This is nothing KIAUH has influence in. Support is provided by Klipper. So if you don't see the board in the list, it is not supported for that feature.

**Comment by DragonFlyer007** [comment]
> This is nothing KIAUH has influence in. Support is provided by Klipper. So if you don't see the board in the list, it is not supported for that feature.

Ok. But what is this future then? 
I know this board supports Klipper at least.

**Comment by th33xitus** [comment]
A feature for flashing MCUs with Klipper that support that feature.
