### ISSUE TITLE
Missing wheel for python on ubuntu 22.04

### ISSUE THREAD

**Issue by kutagh** [th33xitus/kiauh#213]
### Linux Distribution

Ubuntu 22.04

### What happened

During install of Klipper I noticed an error saying Wheel is missing. It recommended to install the following packages:
* python2-setuptools-whl
* python2-pip-whl

After installing those manually and rerunning the install, it successfully completes.

### What did you expect to happen

That those packages were already installed

### How to reproduce

Install Klipper through kiauh on clean minimal ubuntu 22.04 install

**Comment by th33xitus** [comment]
And you decided to install Klipper with python 2.7? or python3.x ?
