### ISSUE TITLE
Filament change error with the new Python 3.x update

### ISSUE THREAD

**Issue by DragonFlyer007** [th33xitus/kiauh#214]
### Linux Distribution

..

### What happened

After installing dual klipper with the new Kiauh 3.x future, i just had errors regarding filament change (M600) on both my printers.

It would throw a "unknown command:  "Y147.2" (or different number) at the point the M600 triggered, then it will park, and when i resume, it travle a tiny bit around the print, then park again, and when resume again, it will throw "Unknown command: #FILAMENTCHANGE" and continiue the print like normal.

Tried all kinda M600, pause and resume codes, but nothing worked, so re-installed Klipper with Python 2.7, and then the same Gcode would print like normal straight away.

### What did you expect to happen

Resume print like normal

### How to reproduce

M600/Filament change

**Comment by th33xitus** [comment]
KIAUH has no influence on how Klipper processes macros installed with Python2 or Python3.
