### ISSUE TITLE
octoprint fails to install when klipper isn't installed

### ISSUE THREAD

**Issue by Nathan22211** [th33xitus/kiauh#216]
### Linux Distribution

Linux mint 20.3, based on ubuntu 20.04

### What happened

upon attempting to install octoprint with the script, it says it's initializing the installation then immediately end the script.ends

### What did you expect to happen

Stuff should show up about the script installing octoprint

### How to reproduce

run the script and attempt to install octoprint. I'm not entirely sure if it's due to my distro or just an issue in your script. So try on ubuntu 20.04 first before trying other distros

**Comment by Nathan22211** [comment]
well found out why. You need some checks to tell the user that klipper needs to be installed before installing octoprint

**Comment by th33xitus** [comment]
Thanks! I found the issue and pushed a fix for it.
