### ISSUE TITLE
Kiauh can't restart multi moonraker instance after update

### ISSUE THREAD

**Issue by yhira1023** [th33xitus/kiauh#218]
### Linux Distribution

debian11

### What happened

There are two instances in my environment.
after update moonraker,failed to restart moonraker.

###### Restarting Moonraker...
Failed to restart moonraker.service: Unit moonraker.service not found.

### What did you expect to happen

Run two incetances

  moonraker-1.service                                                                       loaded    inactive dead    Starts Moonraker 1 on startup
  moonraker-2.service                                                                       loaded    inactive dead    Starts Moonraker 2 on startup
● moonraker.service                                                                         not-found inactive dead    moonraker.service

### How to reproduce

It happens everytime update.

### Additional information

this issue may not be happened  after clean install.
but I have not tried yet.

**Comment by th33xitus** [comment]
Moonrakers own update manager doesn't handle multi instance installations.
It's best to update such setups with KIAUH, as the services will get restarted properly.

A workaround is, to use the Moonraker update manager (from within Mainsail/Fluidd/etc.) and then restart each individual Moonraker service manually via the webinterfaces service control menu.

**Comment by yhira1023** [comment]
Thanks for the reply.
