### ISSUE TITLE
Theme install fails if any folder present in config folder

### ISSUE THREAD

**Issue by jatson** [th33xitus/kiauh#222]
### Linux Distribution

Ubuntu 20.04.4 LTS (GNU/Linux 5.4.164-235 armv7l)

### What happened

I have a folder inside my "klipper_config" folder called "archived" to store the old configuration files.
This leads to a failure during automated mainsail theme install: the ".theme" folder will be placed into the subfolder.
Please see the screen attached about the install log:
![image](https://user-images.githubusercontent.com/3874067/178820938-3cf93e52-7e96-4100-818d-fe443122947a.png)

### What did you expect to happen

I would expect that the target directory is not any subdirectory inside the "klipper_config" folder but the folder itself

### How to reproduce

- create any sub directory inside the "klipper_config" directory manually. For eg.: "mkdir ~/klipper_config/archived/"
- run the theme installer (Main Menu --> 4) Advanced --> 6) Theme installer)
- install any of the themes (I've tried the "1) [Dracula]" )

### Additional information

Running the following command will help to solve the problem and the theme will be able to run properly:
"mv klipper_config/archived/.theme/ klipper_config/"

**Comment by th33xitus** [comment]
Hey, thanks for the report. I just pushed a fix to this issue. Feel free to update KIAUH and confirm if the issue has been resolved. In my tests, the themes now get correctly installed.

**Comment by jatson** [comment]
Hey, confirmed. Works like charm!
Thanks for the quick fix!
