### ISSUE TITLE
The ability to add another instance of klipper and moonraker on top of existing instances.

### ISSUE THREAD

**Issue by MattKelly4D4B** [th33xitus/kiauh#223]
### Is your feature request related to a problem? Please describe

I have to reinstall every time i want to add another printer.  

### Describe the solution you'd like

It would be nice if you could detect the number of instances and add more without having to uninstall all for both klipper and moonraker then reinstall and re-set everything up.

### Describe alternatives you've considered

Uninstalling and reinstalling w more instances.

### Additional information

Please? This tool is pretty much perfect anyways. Thanks.

**Comment by th33xitus** [comment]
Hi, please see: https://github.com/th33xitus/kiauh/issues/130

I just need to find some free time to make it happen 😅
