### ISSUE TITLE
kiauh.sh fails on installing klipper

### ISSUE THREAD

**Issue by jceller** [th33xitus/kiauh#228]
### Linux Distribution

ubuntu

### What happened

When I try to run the klipper install I get the following:
The repository 'http://ports.ubuntu.com/ubuntu-ports impish-security Release' no longer has a Release file.

### What did you expect to happen

To install klipper.

### How to reproduce

run kiuah.sh, option 1, choose klipper, choose recommended python, install 1 instance.

### Additional information

![image](https://user-images.githubusercontent.com/105725351/184512149-d800f75b-942c-47c4-aec6-7c447a0d6efc.png)

**Comment by th33xitus** [comment]
Those error messages come directly from your distro and are unrelated to KIAUH.
