### ISSUE TITLE
alpine linux support

### ISSUE THREAD

**Issue by popeter1** [th33xitus/kiauh#241]
### Is your feature request related to a problem? Please describe

with the shortage of raspberry pi's ive been trying to get klipper working on a spare wyse 3040 thin client but stuck at storage limitations with distros like Ubuntu even when running as bare metal as possble (3040 only has a 8GB eMMC chip so with overhead that leaves only 5GB free for the OS and only ~ 300Mb left over for kiauh)
trying alphine linux as that lighter weight but trying to run the script is a mess there especally as its even giving me a error about not being able to find sudo?

### Describe the solution you'd like

support for alphine linux

### Describe alternatives you've considered

if anybody knows of a diffrent lightwight linux distro that can fit in the size limits of the wyse 3040 eMMC that is also know to work well with kiauh that would be greatly appreciated

### Additional information

the raspberry pi shortage isnt looking likly to let up soon so known ability to run on old thin clients x86 equivlents could be invaluable

**Comment by th33xitus** [comment]
very likely not going to happen anytime soon. so im closing this issue for the meantime.
