### ISSUE TITLE
Crowsnest Install

### ISSUE THREAD

**Issue by mlee12382** [th33xitus/kiauh#243]
### Is your feature request related to a problem? Please describe

Had to install crowsnest separately for multi-cam

### Describe the solution you'd like

Include Crowsnest install either as a separate option or rolled into one of the other installs.

**Comment by th33xitus** [comment]
Yes it is planned, i just haven't found time for implementing it. The plan is to replace mjpg-streamer with crowsnest and just keep the mjpg-streamer installer as an alternative.

**Comment by mlee12382** [comment]
Another thing that would be useful is the installation of the raspi mcu files to control the gpio with klipper.

**Comment by th33xitus** [comment]
That's also on my todo :D

**Comment by Enderlesss** [comment]
Hello th33xitus, I was hoping you could help me with an issue, I installed crowsnest after installing tailscale and 2 instances of klipper.

I keep getting make: *** [Makefile:37: install] Error 1

i have tried unistalling with the same error, i am clueless now. Can you point me in the right direction 

thanks,

**Comment by th33xitus** [comment]
@Enderlesss It's probably the best, if you join the Mainsail Discord and open a new thread in the support forum. In there, your issue can be reviewed and in case there is a bug with Crowsnest, you'll likely get new instructions on how to handle that (maybe creating an issue in the Crowsnest Issue tracker or maybe the Crowsnest-Developer will write it on his Todo-List).
