### ISSUE TITLE
new moonraker update has different needs of configurations

### ISSUE THREAD

**Issue by ramonskie** [th33xitus/kiauh#244]
### Linux Distribution

armbian

### What happened

when installing
- klipper
- moonraker
- fluidd

i do not see any config files. as location is now in `./printer_data/config/`
also some config options are now deprecated.

### What did you expect to happen

a default configuration set for moonraker and printer macros etc

### How to reproduce

fresh install

**Comment by d-nx** [comment]
moonraker.conf also needs to be updated. The current kiauh moonraker install creates a moonraker.conf file with depreciated config sections that prompt errors.

**Comment by th33xitus** [comment]
yes i am aware and i am already working on the changes, im just not so fast 😄 and i want to make sure i don't push garbage code to the repo

**Comment by ramonskie** [comment]
yeah i just happened to run it to it when i did a complete reinstall..
so just wanted to give a headsup.. no rush here as i got it working manually..

**Comment by romanlex** [comment]
@ramonskie can you prodive how did it manually?

**Comment by ramonskie** [comment]
i ran `./kiauh.sh` choose the settings option
change the folder from `/home/username/klipper_config`
to `/home/username/printer_data/config`
copy klipper_config to the printer_data/config
also change the the path to `gcode_files` to `printer_data/gcodes`

i removed the deprecated settings from moonraker.conf.but for some reason it still shows up as a warning.
but the printing works fine from this point on.

**Comment by cristiantrif** [comment]
maybe this change from klipperWrt repo will help https://github.com/ihrapsa/KlipperWrt/commit/31e837c0f748d06f9f27242db81d9396d180053b

**Comment by cristiantrif** [comment]
@th33xitus hope it helps

**Comment by th33xitus** [comment]
@cristiantrif thanks for the link. i already made those changes to kiauh locally. the "problem" is, that kiauh has become much more complex over the time, so i have several other spots to change if i don't want to partially disable functions for the meantime (which i actually don't intend to but maybe its necessary).

**Comment by cristiantrif** [comment]
@th33xitus maybe is easier to use an older version of moonraker for now

**Comment by ramonskie** [comment]
> @th33xitus maybe is easier to use an older version of moonraker for now

the only problem with this is all the auto update scripts for this.+
the moonraker update should just be considered a breaking change from this point

**Comment by th33xitus** [comment]
Personally, i consider it a breaking change, yes. I will also increase KIAUHs major version to version 5 once im ready to push the changes. I won't implement functions to convert old/legacy setups to the new file structure introduced by Moonraker. It's just way too much work and re-installing all components will be much faster in the end.

**Comment by cristiantrif** [comment]
@th33xitus sounds good for me

**Comment by romanlex** [comment]
@ramonskie thx for the instruction
but for me I'm still getting the error "Moonraker requires sudo permission to update the system service. Please check your notifications for further intructions." ((( 
I can't edit any files with fluidd

**Comment by Travis90x** [comment]
> @ramonskie thx for the instruction but for me I'm still getting the error "Moonraker requires sudo permission to update the system service. Please check your notifications for further intructions." ((( I can't edit any files with fluidd

try with this port
http://192.168.0.XXX:7125/
give password to moonraker
if your user is named "pi"
sudo chown -R pi /home/pi/printer_data

**Comment by tficken** [comment]
> i ran `./kiauh.sh` choose the settings option change the folder from `/home/username/klipper_config` to `/home/username/printer_data/config` copy klipper_config to the printer_data/config also change the the path to `gcode_files` to `printer_data/gcodes`
> 
> i removed the deprecated settings from moonraker.conf.but for some reason it still shows up as a warning. but the printing works fine from this point on.

+1 on this working

**Comment by eV1lMoF0** [comment]
I got it running without error and without using a password, have not printed anything yet but it reads the printer and sends commands to the printer like home and move x, y, z

what I did was take the printer.cfg that is in the ~/klipper_config/ directory and modified it like this

1. [include mainsail.cfg]
2. [include /home/USERNAME/printer_data/config/printer.cfg]

then I put all my printers config in the /home/USERNAME/printer_data/config/printer.cfg file

Dont know if this will help anybody, just a quick and dirty way I got it working till they get things worked out

**Comment by ramonskie** [comment]
> > try with this port http://192.168.0.XXX:7125/ give password if moonraker request it if your user is named "pi" sudo chown -R pi /home/pi/printer_data
> 
> I'm trying this several times any passwords are not accepted(from user, form root
so the user you used to run/install kiauh should have sudo rights
and use that users password in the moonraker_url:7125

**Comment by Travis90x** [comment]
I started with a clean ARMBIAN system (debian ARM on a Android TV Box, it's similar to Raspberry OS)
installed Kiauh and than I proceded in this way
![Moonraker](https://user-images.githubusercontent.com/23300077/196500590-40572729-ee55-4d41-81ec-401d612ec221.png)

**Comment by romanlex** [comment]
maybe who known how set sudo password for moonraker in ubuntu?
![image](https://user-images.githubusercontent.com/3369304/196504463-69998dc7-acb9-4f7e-8080-0d718562125f.png)
![image](https://user-images.githubusercontent.com/3369304/196504644-fe09cb4e-c21e-4d36-b2f1-7942610b9b56.png)
![image](https://user-images.githubusercontent.com/3369304/196504724-99174bab-caf7-42c8-a449-269176c4e635.png)

**Comment by romanlex** [comment]
omg 
in my system doesn't exist lost+found directory
![image](https://user-images.githubusercontent.com/3369304/196512722-6ae59cc4-985b-4cae-88ac-f1874167c099.png)
`sudo mkdir /lost+found` resolve issue
![image](https://user-images.githubusercontent.com/3369304/196512634-20d209bc-c625-4e66-a42f-3fb4594e1e05.png)

**Comment by ramonskie** [comment]
nice find.
but why would the code depend on `/lost+found` @th33xitus

**Comment by th33xitus** [comment]
@ramonskie you're asking the wrong person. that is moonraker source code. i can't answer that question.

**Comment by XoBoR** [comment]
Is there an ETA for the new KIAUH version?

**Comment by marbocub** [comment]
I’ｍ very interested in this topic for multiple intances.
How do you plan filenames and directory structures?

for example:
~/printer_data/config/printer_1.cfg
or
~/printer_1_data/config/printer.cfg

**Comment by th33xitus** [comment]
> How do you plan filenames and directory structures?

It will definitely be in the form of `~/printer_1_data/config/printer.cfg`. This file/folder-structure will be easier to handle in the long-term.

No ETA so far. I hope i can get something published this week, maybe a temporarily slimmed down version of KIAUH at least where the most important components like Klipper, Moonraker, Mainsail and Fluidd completely work and the other ones are temporarily disabled until i caught up and applied the changes to them as well. It will probably also include some talking to other devs, especially for Obico and the Telegram Bot.

**Comment by marbocub** [comment]
Thank you.

**Comment by aboktor** [comment]
What is the possibility of pinning the version of moonraker to the last known good version until a fix is worked on? May be something to checkout a specific version of moonraker.

**Comment by th33xitus** [comment]
I just merged the following PR: https://github.com/th33xitus/kiauh/pull/245

Please ALL read the changelog carefully: https://github.com/th33xitus/kiauh/blob/v5.0.0/docs/changelog.md#2022-10-20

**Comment by Travis90x** [comment]
For now Kiauh v5 doesn't support everything, so with a clean OS

```
cd ~
rm -rf ./kiauh
git clone https://github.com/th33xitus/kiauh.git
./kiauh/kiauh.sh
```

install Klipper with python 3, 1 instance, moonraker, mainsail, fluidd port 81.
backup kiauh 5
`mv ./kiauh ./kiauh5`

install Kiauh 4
```
git clone https://github.com/th33xitus/kiauh.git -b v4
./kiauh/kiauh.sh
```
install Klipperscreen, PrettyGCode, MJPEG-Streamer, Gshell command

return to kiauh 5
```
mv ./kiauh ./kiauh4
mv ./kiauh5 ./kiauh
```

If Klipperscreen or others recreate old directories (ex. "klipper_config")
```
mv -v ~/klipper_config/* ~/printer_data/config/
mv -v ~/klipper_logs/* ~/printer_data/logs/
rm -rf ~/klipper_config
rm -rf ~/klipper_logs
sudo ln -s /home/pi/printer_data/config /home/pi/klipper_config
sudo ln -s /home/pi/printer_data/logs /home/pi/klipper_logs
```

If there where Webcamd issues:
with Kiauh4 
```
mv ./kiauh ./kiauh5
mv ./kiauh4 ./kiauh
./kiauh/kiauh.sh
```
remove MJPG-Streamer
reinstall MJPG-Streamer.
return to kiauh 5 (see above)

All tested with Armbian on TV Box Allwinner H6 (T95 max) and webcam Microdia N5 (Sonix_Technology).

**Comment by mirokymac** [comment]
> I just merged the following PR: #245
> 
> Please ALL read the changelog carefully: https://github.com/th33xitus/kiauh/blob/v5.0.0/docs/changelog.md#2022-10-20

Just add a path patch script for V5.0.0.

For machines that installed V4.0.0, just pull update with `kiauh.sh`, then run `path_patch_4to5.sh` will move files accroding `klipper service instance names` to new file structure.

Before patch, `.moonraker_database` and `klipper_config` folders are backup to `~/kiauhV4_config_backup`.

Tested on my 4 machines.

**Comment by th33xitus** [comment]
Sorry, as i already said in an earlier post in this issue, im not really interested in implementing functions for patching/migrating old installs. I seem to see a few flaws in your script also (nothing serious though), so feel free to use them if they work for you. Im likely not going to merge that. Sorry.

**Comment by lokertr** [comment]
Has anyone had any luck with Xubuntu? My install got fouled up from the update so I wiped the system to start fresh. Even doing that though Moonraker complains that the directory Klipper is requesting gcodes from does not match what it expects.   It demands I update it to /home/travis/printer_data/gcodes...tried updating Virtual SDCard in mainsail.cfg.... tried adding it to printer.cfg but no change. I am just currently unable to open any gcode files.

**Comment by larie438** [comment]
Do you have a rough timeline of when KlipperScreen will be available again?

**Comment by th33xitus** [comment]
The installer is available again. Im not 100% sure if everything works out of the box though. KIAUH only executes KlipperScreens own install script, so actually disabling it wasn't really necessary in the first place, i just wanted to have a look at it first when i did that. But again, not 100% sure if maybe some manual intervention is required now. It might be.
