### ISSUE TITLE
Fluidd install fails to download if release for tag doesnt exist

### ISSUE THREAD

**Issue by zbergus** [th33xitus/kiauh#252]
### Linux Distribution

Raspbian GNU/Linux 11 (bullseye)

### What happened

When trying to install Fluidd I get the error below. From what i can gather there is a [tag ](https://github.com/fluidd-core/fluidd/releases/tag/v1.21.1) for v1.21.1 but not a release (latest is v1.21.0) and since service is using release api endpoint it fails.

###### Downloading Fluidd from https://github.com/fluidd-core/fluidd/releases/download/v1.21.1/fluidd.zip ...
--2022-10-25 09:37:11--  https://github.com/fluidd-core/fluidd/releases/download/v1.21.1/fluidd.zip
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-25 09:37:12 ERROR 404: Not Found.

#=======================================================#
 Downloading Fluidd from
 https://github.com/fluidd-core/fluidd/releases/download/v1.21.1/fluidd.zip
 failed!
#=======================================================#

### What did you expect to happen

Fluidd to download via tag or use latest release

### How to reproduce

Fresh install of fluidd, kiauh downloaded today

**Comment by th33xitus** [comment]
I was told that there is a release coming soon. Something went wrong with their workflow.

**Comment by robonxt** [comment]
am experiencing this issue on my machine, it removed my fluidd installation from before when I tried updating from kiauh
