### ISSUE TITLE
KlipperScreen on armbian (lite) needs an extra package to work with touch HDMI screens

### ISSUE THREAD

**Issue by bsas** [th33xitus/kiauh#255]
### Linux Distribution

Armbian 22.08 Jammy (for Le Potato and Renegade Libre Computer boards)

### What happened

KlipperScreen installs and runs fine, but the touch just doesn't work.

### What did you expect to happen

Touch screen on my HDMI screen (those with HDMI and a micro-USB port for "touch") should work out of the box like it does on Raspbian and Raspberry Pi boards.

### How to reproduce

Install "Armbian lite" on a board, then use KIAUH script to install KlipperScreen and use a HDMI/USB touch screen. Screen will show up but the touch will not work.

### Additional information

After a lot of debug I found that some "lite" distros don't come with the "xserver-xorg-input-libinput" package installed. I just did:
 
sudo apt-get install xserver-xorg-input-libinput
 
And everything worked perfect.

I suggest adding this lib to the default KlipperScreen installation script.

**Comment by th33xitus** [comment]
Im unsure if KIAUH should take care of dependencies. I think the KlipperScreen project should take care of it. So i suggest you take the issue there first. Maybe they implement the dependency in their install script. As KIAUH pretty much only executes their own install script anyways, it would be the better place for the requirement to be checked.
