### ISSUE TITLE
Mainsail NGINX installer removes existing serverblock and hijacks the webserver

### ISSUE THREAD

**Issue by Turbine1991** [th33xitus/kiauh#257]
### Is your feature request related to a problem? Please describe

If you're already using NGINX, it takes over port 80 and removes your serverblock.

### Describe the solution you'd like

Add a serverblock on a different port like Octoprint does and allow the user decide whether they'd like to use port 80. Not everyone dedicates a PI just for their 3d printer.

**Comment by th33xitus** [comment]
Can you explain what exactly is **_removed_** and where and which parts are **_highjacked_**?
The only thing that is removed during the setup of either Mainsail or Fluidd is the default config in `/etc/nginx/sites-enabled/default`.

**Comment by th33xitus** [comment]
That will be hard to distinguish if someone is already using NGINX or not and uses the default configuration. I have to do some testing.
