### ISSUE TITLE
Moonraker 0.7.1-748 breaks file management

### ISSUE THREAD

**Issue by Jericon** [th33xitus/kiauh#259]
### Linux Distribution

Raspbian (Debian 11 Bullseye)

### What happened

After updating to Moonraker 0.7.1-748, file management is broken.  This includes gcode files uploaded and config files.

### What did you expect to happen

Files to still be available

### How to reproduce

Update to the latest moon raker (released 10/14/22)

### Additional information

https://moonraker.readthedocs.io/en/latest/user_changes/

Moonraker now manages files and folders in a primary data folder supplied by the -d (--data-path) command line option. As a result, the following options have been deprecated:
<SNIP>
* config_path in [file_manager]
* log_path in [file_manager]

It seems that this breaks multi-instance functionality, as it defaults to ~pi/printer_data/ for the data root. This directory contains one gcodes and one config directory.  

This can be fixed by changing the systemd file (/etc/systemd/system/moonraker-<instance>.service) to use -d and point to a printer_data directory for each instance.  Then having the gcodes directory within be a symlink to a shared directory for all instances.  Or, keeping it as is would allow each instance to have its own gcode files.  At least this is how I was able to fix my instances.

**Comment by th33xitus** [comment]
Please see: https://github.com/th33xitus/kiauh/blob/master/docs/changelog.md#2022-10-20
