### ISSUE TITLE
Didn’t install octoprint

### ISSUE THREAD

**Issue by kobzzon** [th33xitus/kiauh#263]
### Linux Distribution

Operating System: Armbian 22.11.0-trunk Jammy
Kernel: Linux 5.15.77-flippy-78+0
Architecture: arm64
![65B334F4-D370-4AA5-8DE9-88175CBDB094](https://user-images.githubusercontent.com/95584234/201508602-9dcde594-827b-44d6-826c-40f940582cc1.png)

### What happened

ERROR: Failed building wheel for psutil

### What did you expect to happen

ERROR: Could not build wheels for psutil, which is requi red to install pyproject.toml-based projects

### How to reproduce

Installed octoprint vai KIAUH

**Comment by th33xitus** [comment]
Doesn't look like an issue with KIAUH. If python wheels fail to compile, something else is likely the cause for that.
