### ISSUE TITLE
Shell command error

### ISSUE THREAD

**Issue by rozovwolf** [th33xitus/kiauh#266]
### Linux Distribution

Armbian 22.08.8 jamma

### What happened

There was a problem with the shell command.  When you try to run the wget command via shell command, the command is executed, but the printer is no longer available and you have to reboot the firmware.  This error is repeated if you run a script that uses the wget command

### What did you expect to happen

Should send a get request and not affect printing

### How to reproduce

Run wget command via console

**Comment by th33xitus** [comment]
I don't understand the issue. By reading your description im unsure if its even related to KIAUH in any case. I definitely would need a more detailed description.
