### ISSUE TITLE
Creality sonic pad updates

### ISSUE THREAD

**Issue by smwoodward** [th33xitus/kiauh#274]
### Is your feature request related to a problem? Please describe

I have root access to the Creality Sonic Pad and have been trying to figure out how to install the public repos of the klipper apps.  The main issue that I see is that the Sonic Pad uses everything under init.d and systemd.  I know that Kiauh is not meant to be run under root, but it may have to be with the sonic pad with the way that they have the folders locked down.

### Describe the solution you'd like

To have the script to detect if it's on the sonic pad, and be able to install under init.d in busybox if the sonic pad is detected.

**Comment by th33xitus** [comment]
> I have root access to the Creality Sonic Pad

Are you sure you have **root** access? Can you share the root credentials?

> I know that Kiauh is not meant to be run under root, but it may have to be with the sonic pad with the way that they have the folders locked down.

This is part of the reasons why i will not support the Creality Sonic Pad. It's a mess.

**Comment by smwoodward** [comment]
Is there a way to private message you?  I can send you the process that I used to get root credentials for it, as I don't want it to be public yet as I work to get things figured out a bit.

Additionally, when I posted this request, that was before I found where creality was locking down all of the folder structure, and I should be able to get full access with the creality user account.

**Comment by th33xitus** [comment]
> Is there a way to private message you?

Only on discord, really. You can find me on the official Klipper or Mainsail Discord server.

> I should be able to get full access with the creality user account.

Thats the only user account i am currently aware of, and it has no root access, hency my question if you are sure to really have ROOT access or if its just the still restricted creality:creality account they provided for SSH connection.

**Comment by smwoodward** [comment]
I've sent you a message on Discord.

**Comment by smwoodward** [comment]
<img width="714" alt="Screenshot 2022-12-11 at 9 27 00 AM" src="https://user-images.githubusercontent.com/10227870/206912557-ec1d4785-d7d2-41a9-9820-66525cc76dec.png">
Yes, it's really ROOT access.

**Comment by manu7irl** [comment]
@smwoodward Hi I would like to help you on this please PM me! 
I think I could figure out what's missing.

**Comment by xboxusr666** [comment]
I would be greatly interested in the process to get root, as I'd love to join the search of properly updating the system.  Would you be able to PM this process to me as well?

**Comment by smwoodward** [comment]
> I would be greatly interested in the process to get root, as I'd love to join the search of properly updating the system. Would you be able to PM this process to me as well?

Message me on discord.  Michael W#7177
