### ISSUE TITLE
E: Unable to locate package python3-libgpiod on AMD64 ubuntu 18.

### ISSUE THREAD

**Issue by anand-010** [th33xitus/kiauh#285]
### Linux Distribution

UBUNTU 18.04 AMD64

### What happened

I have updated python from 3.6 to 3.10 after i've tried to install moonracker and i've got error E: Unable to locate package python3-libgpiod.

### What did you expect to happen

Installation of moonracker

### How to reproduce

Try to install on non arm debian.

**Comment by ian185987** [comment]
hi,sorry for being this late. but there is any update here? i'm having the same issue
