### ISSUE TITLE
No option to remove mjpgstreamer

### ISSUE THREAD

**Issue by simpat1zq** [th33xitus/kiauh#291]
### Linux Distribution

All

### What happened

So I was excited to see that you added crowsnest. However, since you remove mjpgstreamer, there's no option in Kiauh to uninstall it. At least none that I could find. Is there at least a manual way to remove it, or perhaps add it back in to the remove menu?

### What did you expect to happen

remove mjpgstreamer. 

### How to reproduce

Try to remove mjpgstreamer through kiauh.

**Comment by th33xitus** [comment]
You are right. Although (i think) crowsnest will remove mjpg-streamer if it detects an installation, it is probably smarter (and less confusing) to still have that remove option in KIAUH. My bad, i will re-add it.
