### ISSUE TITLE
Crowsnest could not be installed

### ISSUE THREAD

**Issue by dapengg** [th33xitus/kiauh#295]
### Linux Distribution

Armbian 23.02.0-trunk Bullseye with Linux 6.1.10-flippy-81+

### What happened

![QQ截图20230212163643](https://user-images.githubusercontent.com/64346391/218301767-68ab2d85-39ec-46fc-88d2-09f77df51ba7.png)
![QQ截图20230212165324](https://user-images.githubusercontent.com/64346391/218301789-46c6b5b8-b56e-4df6-b330-f89563c192d0.png)
![QQ截图20230212165249](https://user-images.githubusercontent.com/64346391/218301793-0818af6b-e246-4b35-87ea-aa2070585415.png)

### What did you expect to happen

Reinstallation does not take effect and cannot be uninstalled

### How to reproduce

Reinstallation does not take effect and cannot be uninstalled

**Comment by th33xitus** [comment]
Seeing all those permission denied messages lead me to the conclusion that something else must be wrong with your system or, obviously, with the current users permissions you run all those steps on. Hence i currently doubt that it's an issue with KIAUH or crowsnest.

**Comment by MS1987** [comment]
I met the same issue. And I can confirm that all was well last week. So I think it is relative with the updates of these days. @th33xitus
