### ISSUE TITLE
Use fork of KlipperScreen

### ISSUE THREAD

**Issue by hyptx** [th33xitus/kiauh#298]
### Is your feature request related to a problem? Please describe

No. 

### Describe the solution you'd like

I am looking for a way to change KlipperScreen to a fork. I know you can switch Klipper to a custom repo, can you switch KlipperScreen, if so how?

**Comment by th33xitus** [comment]
That's currently only possible if you modify KIAUHs source code: https://github.com/th33xitus/kiauh/blob/master/scripts/globals.sh#L52
There are no configuration options in place currently.

**Comment by hyptx** [comment]
Thanks for the fast reply. I'm elbow deep in KlipperScreen mods and this solution should work great for my purposes.
