### ISSUE TITLE
index-pack failed

### ISSUE THREAD

**Issue by rafaelldavid** [th33xitus/kiauh#307]
### Linux Distribution

Armbian 23.02.2 Bullseye with Linux 4.4.194-rk322x

### What happened

![image](https://user-images.githubusercontent.com/22876281/222649573-3d68c1ff-b62e-4506-abdb-c6faa72202b3.png)

### What did you expect to happen

I installed Kiauh and when I select to install Klipper, the program downloads the files but ends up with this error. (PS: Sorry if this is not the right place to post)

### How to reproduce

./kiauh/kiauh.sh

Option 1-1 with python3 and 1 instance of Klipper.

**Comment by rafaelldavid** [comment]
![image](https://user-images.githubusercontent.com/22876281/222650142-f48f6e97-b69e-45e8-ada4-29ff4f8ae253.png)

**Comment by th33xitus** [comment]
Im sorry but this is not a KIAUH issue or bug, it seems like its some issue with your network connection and the cloning (download) of Klipper failed due to that. Nothing i can do for you. Sorry.

**Comment by rafaelldavid** [comment]
Can you tell what could be going on? It is connected to the internet by cable. The internet here is stable...

**Comment by rafaelldavid** [comment]
Now a different error appears:

Cloning into '/home/rafael/klipper'...
remote: Enumerating objects: 43729, done.
remote: Total 43729 (delta 0), reused 0 (delta 0), pack-reused 43729
Receiving objects: 100% (43729/43729), 116.31 MiB | 3.26 MiB/s, done.
Resolving deltas: 100% (33901/33901), done.
fatal: did not receive expected object a8687520a3e42acee698e59bc7577d172e72ff98
fatal: index-pack failed
