### ISSUE TITLE
Mainsail using port 80

### ISSUE THREAD

**Issue by shawnp30** [th33xitus/kiauh#31]
Hello. Please excuse my ignorance on the topic. I am trying to install and use fluidd. I already have mainsail installed and running. When I use kiuah to install fluidd it tells me main sail is using port 80 and u need to pick another port. I picked 81. How do I log into fluidd to use the ui

**Comment by th33xitus** [comment]
Hi. Thats easy. You take the same adress you enter in your browser to reach Mainsail and just append the port to it.
So lets say Mainsail is running under `192.168.0.123`, to reach Fluidd you just type in `192.168.0.123:81`.
