### ISSUE TITLE
Fatal: unable to access 'https://github.com/Klipper3d/klipper/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by Vimknight** [th33xitus/kiauh#315]
### Linux Distribution

Debian11

### What happened

Running Debian via Linux deploy on android. SSH into debian terminal via PuTTy on PC or locally via Termux and run
`sudo apt update ` this correctly checks the repositories and updates debian. `cd ~` + `sudo git clone https://github.com/th33xitus/kiauh.git` grabs the script for me. However trying to run the script throws the error in the title when installing any components and trying to `sudo kiauh.sh' throws an exception about not running as root (added by you)

Any idea of ways around this?
I've tried `sudo usermod -a -G aid_inet,aid_net_raw root` Any other ideas would be great

### What did you expect to happen

Expected behaviour was for klipper to be cloned to my device.

### How to reproduce

Run Debian via Linux deploy on android. SSH into debian terminal via PuTTy on PC or locally via Termux, install git and run `git clone https://github.com/th33xitus/kiauh.git` for the same error.

**Comment by th33xitus** [comment]
> Any idea of ways around this?

No, there is a reason why it was implemented to disallow the script to be run under the root user.
Create a new user and then run the script again.
