### ISSUE TITLE
scripts/backup.sh: line 31: backup_octoeverywhere: command not found

### ISSUE THREAD

**Issue by sammcj** [th33xitus/kiauh#316]
### Linux Distribution

Armbian (latest stable), RockPi 4 SE

### What happened

Running update (all) results in an error:

```
...
scripts/backup.sh: line 31: backup_octoeverywhere: command not found
rockpi:kiauh:% find . |grep -i backup_octo                                                                                                                                           <master>
```

I can't see any similar named scripts in the repo:

```
rockpi:kiauh:% find . |grep -i backup                                                                                                                                                <master>
./scripts/backup.sh
./scripts/ui/backup_menu.sh
```

### What did you expect to happen

Updates to work

### How to reproduce

Run an update all, from the latest master (ae9e79c579e890eee451ce480db670ee633eecba)

**Comment by th33xitus** [comment]
Those backup functions still require some work and need to be updated to make use of the new klipper folder structure. So i currently "fixed" the issue by disabling the backup function before component updates. as the backup functions don't correctly work at the moment anyways.
