### ISSUE TITLE
Github Certificate is not trusted/expired

### ISSUE THREAD

**Issue by ShayneDATS** [th33xitus/kiauh#321]
### Linux Distribution

Raspberry Pi OS (64-bit) 2023-02-21

### What happened

Attempted to install mainsail but got a number of errors related to github certificates
![CleanShot 2023-03-24 at 14 47 37](https://user-images.githubusercontent.com/31411908/227637057-c5d28513-78bf-4dcb-baae-3835b2e9950a.png)

### What did you expect to happen

Mainsail gets installed

### How to reproduce

Attempt to install Mainsail

**Comment by th33xitus** [comment]
Try again, looked like a temporary github issue.
