### ISSUE TITLE
Second koonraker/klipper won't start instance

### ISSUE THREAD

**Issue by DuckersMcQuack** [th33xitus/kiauh#324]
### Linux Distribution

Rasbian, or whichever kiauh uses.

### What happened

Second klipper/koonraker instance won't start up.
![NVIDIA_Share_Y7XjSyKslI](https://user-images.githubusercontent.com/9039370/229336856-bf5b7bcc-e64c-44f8-b0a7-24fe420f6dfb.png)

### What did you expect to happen

both to start up as normal and run normally

### How to reproduce

Unplug power cable for pi (pi 4 in my case) and connect it a few days later, suddenly second instance won't start. Nor does the pi want to boot with the second printer connected over usb.

**Comment by th33xitus** [comment]
> Nor does the pi want to boot with the second printer connected over usb.

Not a KIAUH issue then.
