### ISSUE TITLE
Configure Raspberry Pi Camera and streaming during install

### ISSUE THREAD

**Issue by phuzzyday** [th33xitus/kiauh#344]
### Is your feature request related to a problem? Please describe

After installing klipper/moonraker/fluidd, any attempts to set up the raspberry pi camera in the GUI fail. This is a fantastic script guys! This just seems like a feature that would hugely improve the experience!

### Describe the solution you'd like

Ideally, the camera would be configured in fluidd, but at least, the underlying software should be configured so that it can be added in fluidd settings.

### Describe alternatives you've considered

The only thing I can think of is USB cameras as a workaround, but I have my cam mounted on an arm.

### Additional information

Pi3B, Pi Camera compatible. Works effortlessly in octoprint. Reinstalled complete system several times, going from minimum essentials to several plugins.

**Comment by th33xitus** [comment]
What kind of configuration are you asking about? Im very inexperienced with the overall setup and configuration procedure of webcams as i simply do not need or use any. But i think, in crowsnest for example you should be able to do all configurations within the config file of crowsnest? (not entirely sure on that one as well). and that could be done through the file editor of fluidd or mainsail.
