### ISSUE TITLE
add info to Wiki

### ISSUE THREAD

**Issue by FireflyJar** [th33xitus/kiauh#345]
### Is your feature request related to a problem? Please describe

I couldn't figure out how to get to OctoPrint,  wasted a lot of time trying.

### Describe the solution you'd like

Please add info in wiki :    to access OctoPrint , use port :5000,   ex:   yourPiAddress.:5000

Thanks

**Comment by th33xitus** [comment]
You just need to watch the terminal output after the installation:
![image](https://github.com/th33xitus/kiauh/assets/31533186/971be688-ddf8-4391-9495-46313bfea49f)

**Comment by FireflyJar** [comment]
yup,  I need a reminder.   Did this install weeks ago and don't remember it..    few weeks I will also forget I posted this. ;)
