### ISSUE TITLE
Multiple instances after install 

### ISSUE THREAD

**Issue by HinataKato** [th33xitus/kiauh#349]
### Is your feature request related to a problem? Please describe

I recently got another printer, and the current version of kiauh doesn't let me install a new instance

### Describe the solution you'd like

Let user add new instance by editing the old one, then add the new one 

### Describe alternatives you've considered

Remove and reinstall it

**Comment by th33xitus** [comment]
Duplicate of https://github.com/th33xitus/kiauh/issues/130
