### ISSUE TITLE
Unable to determine Mainsail latest version on Update

### ISSUE THREAD

**Issue by menthol1979** [th33xitus/kiauh#350]
### Linux Distribution

Raspbian bullseye

### What happened

When I tried to update all components, I saw that KIAUH was unable to determine the latest version of Mainsail

### What did you expect to happen

I was expecting to show the latest version available. Instead, I sww "download"

### How to reproduce

Update all via menu

### Additional information

![Screenshot 2023-06-07 170840](https://github.com/th33xitus/kiauh/assets/70651211/0ce9c1eb-1a9d-4590-a7f3-e6cbfa422107)

**Comment by menthol1979** [comment]
Thanks mate :) It works fine now

**Comment by th33xitus** [comment]
Thanks for the quick feedback :)
