### ISSUE TITLE
[ENHANCEMENT] Add support for fluidd

### ISSUE THREAD

**Issue by tionebrr** [th33xitus/kiauh#36]
Hello,
There is this neat front-end you might want to add support to:
https://github.com/cadriel/fluidd

**Comment by th33xitus** [comment]
Hi,
You are about a month too late with that request 😛😄 
https://github.com/th33xitus/kiauh/blob/master/docs/changelog.md#2020-10-06

**Comment by lixxbox** [comment]
I wonder how one could miss that? It literally jumps at you when you open the script and look around?

**Comment by tionebrr** [comment]
OMG I need more sleep.
Sorry for the noise.
