### ISSUE TITLE
Arch and ArchARM usage guide/documentation

### ISSUE THREAD

**Issue by montyx99** [th33xitus/kiauh#362]
### Is your feature request related to a problem? Please describe

I use arch linux on most of my servers. Both Arch for x86-64 and ArchArm on RPI. I have issues with the usage of the awesome kiauh.

### Describe the solution you'd like

Provide usage guide/documentation for Arch Linux and ArchArm. The PacMan package controller cannot handle the kiauh request out of box.

### Describe alternatives you've considered

Currently I have to use a Debian based OS on a separated server.

**Comment by th33xitus** [comment]
There is currently no technical implementation in KIAUH to support arch. Therefore a guide/documentation is also not available.
