### ISSUE TITLE
Self update option?

### ISSUE THREAD

**Issue by th3fallen** [th33xitus/kiauh#41]
Any thoughts for the ability to self update kiauh along with the other stuff in the update menu?

**Comment by th33xitus** [comment]
There is actually an update notification in bright yellow in the main menu if there were new commits to KIAUH.
![](http://puu.sh/GQtTS/6722e7fe13.png)
Is that not okay? Not sure if there needs to be a separate entry in the update menu then?

**Comment by th3fallen** [comment]
ah that's totally fine i ddint realize it did that. thanks!

**Comment by th33xitus** [comment]
I see, actually you are not the first person not really noticing that notification. There were several people overlooking it. :D 
Maaaaybe i will think about a different, more prominent way to display a possible update, but for now i would stick to that notification :)
