### ISSUE TITLE
Problems updating scurve-shaping branch

### ISSUE THREAD

**Issue by 1N4148** [th33xitus/kiauh#42]
Get this when trying to update scurve-shaping branch:

###### Checking out dmbutyugin
error: pathspec 'dmbutyugin' did not match any file(s) known to git

Installed Klipper, Moonraker & Fluidd with Kiahu, switched also from master to scurve-shaping, but now I cannot update with Kiahu.

Manual update is working:
>git fetch dmbutyugin
>git checkout dmbutyugin/scurve-shaping

**Comment by th33xitus** [comment]
Thanks for the report, i will have a look at it tomorrow.

**Comment by th33xitus** [comment]
I was able to reprocude the error. I think i solved the issue, it was a typo in the update function.
Can you please update KIAUH and try again please? In my tests, everything worked fine again now.

**Comment by 1N4148** [comment]
Looks good, but meanwhile I've updated the branch manually.

But doing an update on the same branch doesn't show the error message anymore :)
