### ISSUE TITLE
Feature request: Is it possible to do updates to Fluidd?

### ISSUE THREAD

**Issue by DeviousPenguin** [th33xitus/kiauh#45]
I'm currently on Fluidd 0.1.0 according to the WebUI, but kiauh is saying that 1.0.0 is avaliable.

Is there a way to do this update using kiauh at all? Thanks

**Comment by lixxbox** [comment]
Yes

**Comment by DeviousPenguin** [comment]
Thanks, up until now I was using the 'update all' function, and it wasn't updating fluidd for some reason, but I tried the Fluidd specific option (6) and it seems to have updated OK and am now on V1.0.0 :)
