### ISSUE TITLE
dwc timeout

### ISSUE THREAD

**Issue by shawnp30** [th33xitus/kiauh#51]
when i install dwc i can see connection established. when i try and connect the printer i get a timeout error. using the standard ip address with port ending in 4750. i am using a bigtreetech gtr v1.0 motherboard, could this be why im not able to connect to dwc?
![image](https://user-images.githubusercontent.com/20215592/102109492-1a7a2000-3e02-11eb-87e4-59309966fd31.png)

**Comment by th33xitus** [comment]
Sorry i only provide the installation script and can't support further malfunctions myself.
Maybe try and ask for help on the Klipper Discord or in the github repo of the creator if the dwc2-forklipper-socket translator: https://github.com/Stephan3/dwc2-for-klipper-socket
