### ISSUE TITLE
Wrong question in moonraker installation process

### ISSUE THREAD

**Issue by Tomblarom** [th33xitus/kiauh#53]
Just a small bug I guess. While installing moonraker, it asks if it should disable Ocotoprint for you, since it may interfere with Mailsail, which isn't even installed in my case. 

![image](https://user-images.githubusercontent.com/12703270/103150687-abdc8100-4776-11eb-9dfe-3e4d2db72c7c.png)

**Comment by th33xitus** [comment]
Thanks for reporting. I should reword that question now since there are Mainsail, Fluidd and Klipperscreen making use of Moonraker.

**Comment by th33xitus** [comment]
Should be solved with 16e6dde99864bc0c315f483c036938728ae597ba

Closing...
