### ISSUE TITLE
KlipperScreen Installation nothing happens?

### ISSUE THREAD

**Issue by nicedevil007** [th33xitus/kiauh#59]
Heya, I installed KlipperScreen with root before.
Now I removed the service and tryed to install it with your script.

Nothing more than this is happening/showing to me ?

![image](https://user-images.githubusercontent.com/17103076/105233304-f5e43700-5b69-11eb-8bfd-45d340227190.png)

**Comment by th33xitus** [comment]
@jordanruthe Any idea on that issue?

**Comment by jordanruthe** [comment]
@th33xitus https://github.com/th33xitus/kiauh/pull/60 This should fix that issue. I had the same problem and the patch worked afterwards

**Comment by th33xitus** [comment]
Cool, merged. Thanks for the quick response!

@nicedevil007 would be nice if you can give feedback if this patch solves the issue.

**Comment by nicedevil007** [comment]
Seems to work :) thank you, was able to update as well now!

![image](https://user-images.githubusercontent.com/17103076/105249035-ba506980-5b77-11eb-87a9-d017b11aeeb6.png)
