### ISSUE TITLE
Can Octopi be installed along with the other options?

### ISSUE THREAD

**Issue by michelluccote** [th33xitus/kiauh#66]
Looking at the installation I can't tell if I can still install Octoprint even if my main setup it Moonraker/Mainsail/Fluid/KlipperScreen? I'm asking because I would like to occasionally plug the PI to a different printer and monitor a run and send some g-code commands. Since the UI allows me to install it I can't tell if they are mutually exclusive or can run independently from one another?

**Comment by th33xitus** [comment]
@michelluccote Yes you can have all interfaces installed at once and basically use them all at the same time. Well... that is of course not really recommended but still possible.
