### ISSUE TITLE
Moonraker fails to start after upgrade

### ISSUE THREAD

**Issue by mjoconr** [th33xitus/kiauh#69]
Hi
I'm getting an error after upgrading Moonraker v0.4.1-4
No matter what I do Moonraker is failing to find the printer config
[moonraker.log](https://github.com/th33xitus/kiauh/files/6096906/moonraker.log)

Any ideas ?

**Comment by mjoconr** [comment]
Ok, well it was not actually a moonraker error is was the start script for klipper for systemd. I did not edit this so the issue must have been in kiaud when it upgraded klipper.

**Comment by th33xitus** [comment]
```
Unable to open config file /home/pi/klipper_config/home/pi/klipper_config/printer.cfg
```
This is impossible to happen with only upgrading Moonraker or Klipper because no config or no service will be rewritten/modified during upgrading. You did something else, to mess this up somehow.

Do you have it solved by now? Or do you still need help?
