### ISSUE TITLE
No mjpg streamer when install via kiauh

### ISSUE THREAD

**Issue by jonathanoeijoeng** [th33xitus/kiauh#73]
Could you help to add mjpg streamer in kiauh?
I have installed klipper, moonraker and fluidd via kiauh and found there is no mjpg streamer in my installation comparing when i install via fluiddpi image.

**Comment by NovaViper** [comment]
Can confirm the same issue here on my Raspberry pi 4

**Comment by th33xitus** [comment]
Fixed with 104089e :)

**Comment by persano** [comment]
Did not want to open a new issue, but mjpg streamer is broken or disabled in 5.0.0 

" Function currently disabled! Sorry! " is the error

**Comment by Creo2005** [comment]
export KIAUH_SRCDIR=${HOME}/kiauh
export PRINTER_DATA=${HOME}/printer_data
export KLIPPER_CONFIG=${PRINTER_DATA}/config
export SYSTEMD=/etc/systemd/system
export KLIPPER_LOGS=${PRINTER_DATA}/logs
source ${KIAUH_SRCDIR}/scripts/utilities.sh
source ${KIAUH_SRCDIR}/scripts/mjpg-streamer.sh
install_mjpg-streamer

**Comment by djObsidian** [comment]
@Creo2005 what is this? I should paste this into console? Or in kiauh.sh?

**Comment by olivierchaput** [comment]
Hey @djObsidian, paste it into the console. Worked flawlessly for me! Thanks @Creo2005

**Comment by JDPS** [comment]
Genius... simple and functional. Thanks.

**Comment by SimonSolar2C** [comment]
Tried the above commands - was looking good but then got stuck.
Anyone know how to fix this?

###### Initializing MJPG-Streamer installation ...

###### Checking for the following dependencies:
● git
● cmake
● build-essential
● imagemagick
● libv4l-dev
● ffmpeg
● libjpeg62-turbo-dev

###### Installing the following dependencies:
● imagemagick
● libv4l-dev

-bash: : No such file or directory
