### ISSUE TITLE
Deleting ~/.octoprint folder in backup.sh script

### ISSUE THREAD

**Issue by flajzi** [th33xitus/kiauh#74]
When KIAUH runs backup.sh and defines all backup functions, there is outside any function a block of code (lines 89-94) which tries delete ~/octoprint* folder. Luckily for us function status_msg is not defined yet and it just print an error when you start KIAUH:
`/home/pi/kiauh/scripts/backup.sh: line 92: status_msg: command not found`

**Comment by th33xitus** [comment]
Thanks for reporting that issue!
That really shouldn't have happened...
Lesson learned, never copy and paste codeblocks you want to re-use if it's too late and you just forget to remove that 😅
