### ISSUE TITLE
gcode upload fails due to nginx error 413 with fluidd

### ISSUE THREAD

**Issue by fookatchu** [th33xitus/kiauh#77]
removal of the client_max_body_size parameter in a recent commit seems to be the culprit. The installed config differs from the one supplied with stock fluidd. 
If client_max_body_size is reset to 0, upload of bigger files work again.

**Comment by th33xitus** [comment]
Thanks for reporting!
Should be fixed then with the changes made in 865fbc07dcb04bd5db4fe6018332d67b7910633d
