### ISSUE TITLE
Confirmed Working on Armbian/Zero Pi

### ISSUE THREAD

**Issue by marcdraco** [th33xitus/kiauh#81]
First of all, thank you for this script which has saved me a ton of faffing around that I simply don't have time for.

I also couldn't find my RPi Zero jar (yes, I have a jar of them) so I found a FriendlyElec Zero Pi looking lonesome and figured... 

Long story short, although it's tiny bit tight on memory (it's swapping a little but I DO have both interfaces running just for stuff and giggles) your script worked first time and without a hitch!

I don't know if you want to add this to your documentation but you certainly deserve a pat on the back sir!

**Comment by th33xitus** [comment]
Hi, thank you for your feedback!
I am glad it worked right out of the box and without any hassle.

I made a note and will then probably list Armbian under the supported OS once i get around updating the docs and readme again.

Thanks!
