### ISSUE TITLE
FR: Adding Telegram bot to the installer

### ISSUE THREAD

**Issue by zztopper** [th33xitus/kiauh#83]
It'd be useful and convenient if you've added [this Telegram bot](https://github.com/nlef/moonraker-telegram-bot) to the installer script.

**Comment by tjengbudi** [comment]
@th33xitus i tried 2 telegram bot for moonraker. the other is https://github.com/Raabi91/moonraker-telegram

this one is more lightweight. 
with telegram-bot my system got hot. but telegram-bot can send video and have more feature (might be gimmick)

**Comment by nlef** [comment]
PR #117

**Comment by th33xitus** [comment]
> PR #117

Yup, please fix the pending reviews so i can test it :) Thanks in advance!

**Comment by th33xitus** [comment]
Merged :)

Feature was added!
