### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by BisSpaeterDannnoch** [th33xitus/kiauh#84]
Hi 
important things first - Thank you  - I am grateful for your work.

Just the question, while installing the script tells me python 2.7 (pip) is not supported from Jan 2021 any more.
Anything I have to observe here?
Script is running fine anyhow.

Thank you

**Comment by th33xitus** [comment]
You can ignore that message :)

**Comment by BisSpaeterDannnoch** [comment]
Wow. That was fast.  Thank you again.Enjoy this day off :-)
-------- Ursprüngliche Nachricht --------Von: th33xitus ***@***.***> Datum: 24.05.21  09:34  (GMT+01:00) An: th33xitus/kiauh ***@***.***> Cc: BisSpaeterDannnoch ***@***.***>, Author ***@***.***> Betreff: Re: [th33xitus/kiauh] Python 2.7 (#84) 
You can ignore that message :)
