### ISSUE TITLE
Multiple webcamd?

### ISSUE THREAD

**Issue by nibblerrick** [th33xitus/kiauh#87]
Hi,

thank you very much for this handy piece oft software!

I wanted to ask if you could consider installing multiple webcamd's with the script?
Doing manually what the script does to create another instance works (with adjusted filenames, of course) so I wondered if it could be achieved with the installer.

If you think this isn't something which belongs in your script feel free to close the issue right away.

Thanks!

**Comment by th33xitus** [comment]
There is something in the planning. I have no ETA yet but yes, soon you should be able to run multiple webcams :)

**Comment by nibblerrick** [comment]
That sounds awesome, thanks!

**Comment by th33xitus** [comment]
KIAUH now uses the same NGINX configurations when installing Moonraker and Mainsail/Fluidd as they are used in MainsailOS or FluiddPi. That means it's possible to have up to 4 webcams at the same time. Those are configured each with their own webcam.txt file (webcam1.txt, webcam2.txt, ... ) in the klipper_config directory.

That way all webcams share the same webcamd service, which is pretty nice :)

**Comment by nibblerrick** [comment]
Thank you!

**Comment by leandrotoledo** [comment]
Sorry to revive this one, but are there any additional instructions on how to setup multiple webcams?

I have two USB webcams in a multiple Moonraker/Klipper setup but only one instance of webcamd is spawned.

**Comment by apphead** [comment]
In /home/pi/kiauh/resources/mjpg-streamer, I put webcam.txt and webcam2.txt and configured two cameras in settings. However, the config of webcam2.txt seems to never get picked up, resulting in the same camera displayed twice. Any ideas?

**Comment by apphead** [comment]
Stupid me. I tried changing the port in (mainsail) camera settings, when all I needed to do is to squeeze a 2 in as in 
/webcam2?action=
 :laughing: :laughing: :laughing: :laughing:
![image](https://user-images.githubusercontent.com/505490/201438998-266c7123-4513-46d4-8f32-7bc318f9869a.png)
