### ISSUE TITLE
Failed moonraker install

### ISSUE THREAD

**Issue by revnull-src** [th33xitus/kiauh#95]
On a clean install of Raspberry Pi OS Lite:
```
###### Installing python virtual environment...
/home/pi/kiauh/scripts/install_moonraker.sh: line 177: virtualenv: command not found
ln: failed to create symbolic link '/home/pi/moonraker-env/lib/python*/site-packages': No such file or directory
/home/pi/kiauh/scripts/install_moonraker.sh: line 182: /home/pi/moonraker-env/bin/pip: No such file or directory
<!!!!> There is already a file called 'moonraker.conf'!
<!!!!> Skipping...
```
Resolved by uninstalling moonraker with KIAUH, `sudo apt install virtualenv`, reinstalled moonraker with KIAUH, profit.

**Comment by th33xitus** [comment]
Im not sure what happened on your side but `virtualenv` gets installed as a dependency during the Klipper installation.
Therefore it shouldn't be missing during a Moonraker installation.

I just set up a new SD card with a fresh RaspberryPi OS image and tested it myself. No issue here, the Moonraker installation went through without an issue.

Anyways, i will add virtualenv explicitly to the second dependency check so the script checks again for that package to be installed. 

Thanks for reporting.
