### ISSUE TITLE
Adding PrettyGCode to the installer

### ISSUE THREAD

**Issue by Kragrathea** [th33xitus/kiauh#99]
Hi! I am getting ready to release a new GCode visualizer called PrettyGCode (see below). It used to be an OctoPrint plugin but now I am porting it to a stand alone web app that uses the moonraker API to get print status. It needs to be installed on the Raspberry Pi similar to how Fluidd is installed.  It is a single Nginx website with no other dependencies other than Moonraker. 

Using Kiauh for distribution and updating would be ideal, since I plan to eventually support all the different UIs (Fluidd,OctoPrint, Duet, Mainsail).  Would you be interested in collaborating on adding PrettyGCode into Kiauh? 
[PrettyGCode for Klipper](https://github.com/Kragrathea/pgcode)
[PrettyGCode for OctoPrint](https://github.com/Kragrathea/OctoPrint-PrettyGCode)

**Comment by th33xitus** [comment]
Hey. I just added an installer for PrettyGCode with https://github.com/th33xitus/kiauh/commit/05842f8e1d2bcb4d03bf7d62467037a3a48602f9 😃

I made the port it runs on customizable for the user (it will default to 7136 though). 
I think that can be usefull to some people.

**Comment by Kragrathea** [comment]
Wow! That was amazingly fast. :-) I'll test it as soon as I get home.

**Comment by Kragrathea** [comment]
Works Great! I even tested an update.  Thanks so much th33xitus. Feel free to close this, if any problems come up I will create a new issue.
